### ISSUE TITLE
Bug with pillow==10.0.0 and detectron2==0.6 

### ISSUE THREAD

**Issue by ambroiseb** [Ikomia-dev/IkomiaApi#14]
**Describe the bug**
Algorithms from detectron2 do not load and leads to : module 'PIL.Image' has no attribute 'LINEAR'

**To Reproduce**
Installing ikomia==0.9.2 which has a requirement pillow>=8.1 installs pillow 10.0.0 which is incompatible with detectron2 0.6

**Expected behavior**

**Logs/Screenshots**
If applicable, add logs/screenshots to help explain your problem. Ikomia logs are save in $HOME/Ikomia/log.txt.

**Environment:**
 - OS: [e.g. Windows11, Ubuntu 22.04]
 - Python version [e.g. 3.7, 3.8, 3.9, 3.10]
 - Ikomia API version 0.9.0

**Additional context**

**Comment by LudoBar** [comment]
Maybe we could add upper limit for Pillow (< 10.0.0) in Ikomia-dev/detectron2? 
Ikomia API should be compatible with recent versions of Pillow.
