### ISSUE TITLE
Save a workflow in current folder

### ISSUE THREAD

**Issue by gdemarcq** [Ikomia-dev/IkomiaApi#21]
**Describe the bug**
When I save a workflow in the current folder, I have a runtime error (Invalid argument).

**To Reproduce**

```python
from ikomia.dataprocess.workflow import Workflow

# Init your workflow
wf = Workflow()

# Export your workflow as a JSON file
wf.save("test.json")
```

**Expected behavior**

I would expect it to work.

**Environment:**
 - OS: Linux
 - Python version 3.10
 - Ikomia API version 0.9.2

**Additional context**
If I use the path "./test.json", it works.

```python
from ikomia.dataprocess.workflow import Workflow

# Init your workflow
wf = Workflow()

# Export your workflow as a JSON file
wf.save("./test.json")
```

**Comment by LudoBar** [comment]
Completed in Ikomia-dev/IkomiaCore@bb46e0ec16426aa6ffa0c349a5e797aaf87b3ec3
