### ISSUE TITLE
Not able to run GroundingDino on custom image

### ISSUE THREAD

**Issue by SCLIIITB** [Ikomia-dev/IkomiaApi#23]
**Describe the bug**
I am not able to run the Grounding Dino on a custom image

**To Reproduce**
from ikomia.dataprocess.workflow import Workflow
from ikomia.utils.displayIO import display

# Init your workflow
wf = Workflow()    

# Add the Grounding DINO Object Detector
dino = wf.add_task(name="infer_grounding_dino", auto_connect=True)
# Set the parameters
dino.set_parameters({
    "model_name": "Swin-B",
    "prompt": "leaf .",
    "conf_thres": "0.35",
    "conf_thres_text": "0.25"
})

# Run on your image  
# wf.run_on(path="path/to/your/image.png")
wf.run_on(url="https://github.com/Horea94/Fruit-Images-Dataset/blob/master/test-multiple_fruits/tomatoes1.jpg")

# Inspect your results
display(dino.get_image_with_graphics())
# Display image on Google Colab
from PIL import ImageShow
ImageShow.register(ImageShow.IPythonViewer(), 0)

display(dino.get_image_with_graphics())

**Expected behavior**
bounding box on the leaves

**Logs/Screenshots**
tomatoes1.jpg: 14.8kiB [00:00, 22.9MiB/s]                  

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-11-678225e4487f>](https://localhost:8080/#) in <cell line: 12>()
     10 # Run on your image
     11 # wf.run_on(path="path/to/your/image.png")
---> 12 wf.run_on(url="https://github.com/Horea94/Fruit-Images-Dataset/blob/master/test-multiple_fruits/tomatoes1.jpg")
     13 
     14 

1 frames

[/usr/local/lib/python3.10/dist-packages/ikomia/dataprocess/workflow.py](https://localhost:8080/#) in run_on(self, array, path, url, folder)
    423                 raise RuntimeError("Workflow run failed: unsupported input type.")
    424 
--> 425             self.run()
    426 
    427     def load(self, path):

[/usr/local/lib/python3.10/dist-packages/ikomia/dataprocess/workflow.py](https://localhost:8080/#) in run(self)
    380 
    381         if run_mode == Workflow.RunMode.SINGLE:
--> 382             super().run()
    383             metrics = self.get_time_metrics()
    384             total_time = metrics['total_time']

RuntimeError: <class 'AttributeError'>: 'NoneType' object has no attribute '__array_interface__':   File "/root/Ikomia/Plugins/Python/infer_grounding_dino/infer_grounding_dino_process.py", line 182, in run
    image = self.transform_image(src_image)

  File "/root/Ikomia/Plugins/Python/infer_grounding_dino/infer_grounding_dino_process.py", line 111, in transform_image
    img_pil = Image.fromarray(image).convert("RGB")

  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3069, in fromarray
    arr = obj.__array_interface__
 (Code 18)

**Environment:**
Google Colab Notebook with GPU

**Additional context**
I have followed the code from here : https://gdemarcq.medium.com/unlocking-zero-shot-object-detection-with-groundingdino-a-step-by-step-guide-5956c7f7f58 

It worked well with the given image on the article but the code is not working on any other image.

**Comment by allankouidri** [comment]
Hi @SCLIIITB, for running inferences on an image from GitHub, make sure to use the raw link. You have two options: append ?raw=true to the end of the file URL, or obtain the direct raw link by right-clicking the image and selecting the "Copy Image Address" option.


Please find below an example:

```Python

from ikomia.dataprocess.workflow import Workflow
from ikomia.utils.displayIO import display

# Init your workflow
wf = Workflow()

# Add the Grounding DINO Object Detector
dino = wf.add_task(name="infer_grounding_dino", auto_connect=True)

# Set the parameters
dino.set_parameters({
"model_name": "Swin-B",
"prompt": "tomatoes",
# "prompt": "leaf .",
"conf_thres": "0.35",
"conf_thres_text": "0.25"
})

# Run on your image
# wf.run_on(path="path/to/your/image.png")
wf.run_on(url="https://github.com/Horea94/Fruit-Images-Dataset/blob/master/test-multiple_fruits/tomatoes1.jpg?raw=true")

# Inspect your results
display(dino.get_image_with_graphics())
```

To display the output on Google Colab you can use the following: 
```Python
from PIL import ImageShow
ImageShow.register(ImageShow.IPythonViewer(), 0)

display(dino.get_image_with_graphics())
```

**Comment by SCLIIITB** [comment]
Thank You so much. It worked.

**Comment by SCLIIITB** [comment]
Thank You so much. It worked.
