### ISSUE TITLE
Bug to connect tasks involving CSemanticSegmentationIO as input

### ISSUE THREAD

**Issue by ambroiseb** [Ikomia-dev/IkomiaApi#24]
**To Reproduce**
Create a new workflow, add infer_yolo_v8_instance_segmentation with auto_connect, then add infer_hf_stable_diffusion_inpaint with auto_connect. Make sure infer_yolo_v8_instance_segmentation is not run before connecting the tasks.

**Expected behavior**
Tasks should be linked.

**Logs/Screenshots**
Traceback (most recent call last):
  File "/home/ambroise/Developpement/recherches/test_algos.py", line 11, in <module>
    std = wf.add_task(name="infer_lcm_stable_diffusion_inpaint", auto_connect=True)
  File "/home/ambroise/Developpement/IkomiaApi/ikomia/dataprocess/workflow.py", line 294, in add_task
    self.connect_tasks(parent_task, task)
  File "/home/ambroise/Developpement/IkomiaApi/ikomia/dataprocess/workflow.py", line 364, in connect_tasks
    self.connect(src_id, target_id, -1, -1)
RuntimeError: OpenCV(4.7.0) /home/ambroise/Developpement/opencv/modules/core/src/matrix_expressions.cpp:24: error: (-5:Bad argument) Matrix operand is an empty matrix. in function 'checkOperandsExist'

**Environment:**
 - OS: [e.g. Windows11, Ubuntu 22.04]
 - Python version [e.g. 3.7, 3.8, 3.9, 3.10]
 - Ikomia API version 0.10

**Comment by LudoBar** [comment]
Fixes in Ikomia-dev/IkomiaCore@9e6d915
