### ISSUE TITLE
Unable to install ikomia via pip

### ISSUE THREAD

**Issue by kdudyala** [Ikomia-dev/IkomiaApi#25]
**Describe the bug**
Unable to find ikomia with python3.10 version
ERROR: Could not find a version that satisfies the requirement ikomia (from versions: none)
ERROR: No matching distribution found for ikomia

**To Reproduce**
Create virutalenv by using Python 3.10.13
pip install ikomia

**Expected behavior**

**Logs/Screenshots**
If applicable, add logs/screenshots to help explain your problem. Ikomia logs are save in $HOME/Ikomia/log.txt.

**Environment:**
 - OS: mac version 14.2
 - Python version  3.10.X
 - Ikomia API version 0.10.0

**Additional context**
<img width="660" alt="image" src="https://github.com/Ikomia-dev/IkomiaApi/assets/61959012/a1e6d905-c802-44ff-ac96-4c29cba7bc1f">

**Comment by LudoBar** [comment]
Hello @kdudyala! Thank you for your interest in Ikomia API.

Unfortunately we do not provide pre-built wheels for Mac OS for now.
As we know that more and more developers are working from Mac, we plan to support it in early 2024.

**Comment by kdudyala** [comment]
Thanks for the info @LudoBar 
I am facing below issue while trying to import ikomia on Linux container. 
(env) kdudya@kdudya-mex:~/menu$ python
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import ikomia
Traceback (most recent call last):
  File "/home/user/menu/env/lib/python3.9/site-packages/ikomia/core/__init__.py", line 19, in <module>
    from ikomia.core.pycore import *
ImportError: libusb-1.0.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/menu/env/lib/python3.9/site-packages/ikomia/__init__.py", line 17, in <module>
    from ikomia import utils
  File "/home/user/menu/env/lib/python3.9/site-packages/ikomia/utils/__init__.py", line 15, in <module>
    from ikomia.utils import iklogger
  File "/home/user/menu/env/lib/python3.9/site-packages/ikomia/utils/iklogger.py", line 25, in <module>
    from ikomia.core import config
  File "/home/user/menu/env/lib/python3.9/site-packages/ikomia/core/__init__.py", line 22, in <module>
    from ikomia.lib.pycore import *
ModuleNotFoundError: No module named 'ikomia.lib.pycore'

**Comment by LudoBar** [comment]
Indeed, we depend on libusb-1.0 library and it is often provided by Linux distribution but sometimes not. So if you use Debian, Ubuntu or derived, you just have to do:
`apt install libusb-1.0-0-dev`

It should be almost the same with others Linux distributions with their respective package manager.

**Comment by kdudyala** [comment]
thanks
